const char LOGIN_REQUEST = 1;
const char LOGIN_SUCCESS = 2;
const char LOGIN_FAILED = 3;

const char CREATE_GROUP_REQUEST = 4;
const char CREATE_GROUP_SUCCESS = 5;
const char CREATE_GROUP_FAILED = 6;

const char REQUEST_ALL_GROUPS = 7;
const char REPLY_ALL_GROUPS = 8;

const char REQUEST_PARTICIPATING_GROUPS = 9;
const char REPLY_PARTICIPATING_GROUPS = 10;

const char REQUEST_NON_PARTICIPATING_GROUPS = 11;
const char REPLY_NON_PARTICIPATING_GROUPS = 12;

const char JOIN_GROUP_REQUEST = 13;
const char JOIN_GROUP_SUCCESS = 14;
const char JOIN_GROUP_FAILED = 15;

